spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/taskvault
spring.datasource.username=taskvault
spring.datasource.password=taskvault123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=taskvault-super-secret-key-minimum-256-bits-long-for-hs256
jwt.expiration=86400000